version: '3'

services:
  geminiprochat:
    build: .
    container_name: geminiprochat
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      # - HTTPS_PROXY=${HTTPS_PROXY}
      # - API_BASE_URL=${API_BASE_URL}
      # - HEAD_SCRIPTS=${HEAD_SCRIPTS}
      # - PUBLIC_SECRET_KEY=${PUBLIC_SECRET_KEY}
      # - SITE_PASSWORD=${SITE_PASSWORD}
      # - OPENAI_API_MODEL=${OPENAI_API_MODEL}